### ISSUE TITLE
Add button does not work on some platforms

### ISSUE THREAD

**Issue by yschaeff** [ArjanPeeters/NaamKenmerkToepassing#3]
On some browsers the add button does not work and throws an exception:

"DOMException: Write permission denied."

![image](https://github.com/ArjanPeeters/NaamKenmerkToepassing/assets/6480467/01911d6f-b2ba-4b0d-8a84-ab029ac46cc9)

 I think some platforms require explicit permission to write to the OS clipboard. My JS foo is not good enough to know how to fix it (and the source to obscured to properly read it). But it seems you can make a API call to get this permission https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest .

At the very least the exception should be caught so other functions still work (i.e. Add it to the list).

The problem occured using
- Linux + Qutebrowser
- Android + DuckDuckGo browser

On both platforms it worked fine with FireFox and Chrome/Chromium.

**Comment by ArjanPeeters** [comment]
I have pushed an update to catch the error so you at least get a list. To solve this error for real i have to go to great lenths for a small userbase (Linux in my world is virtually non existent).

I don't have those browsers or linux, so i you would care to test this ;-)

**Comment by yschaeff** [comment]
It works now. It will give a popup with a javascript alert each time you add. Which is annoying but at least functional. Both of these browsers are chromium based (blink engine) other privacy/security oriented browser on that engine might have the same issue? Like Brave perhaps. But I haven't tested this.

**Comment by ArjanPeeters** [comment]
I'm shure they will. Can you give the site permission?

**Comment by yschaeff** [comment]
It seems Blink has a setting 'content.javascript.can_access_clipboard'. Maybe it is possible to set it per domain? Enabling it system wide is a bit of a security issue. For example websites might read your passwords if you copy-paste them between browser and password manager.

A better solution would be to explicit ask for permission:

```
navigator.permissions.query({ name: "clipboard-write" }).then((result) => {
  if (result.state === "granted" || result.state === "prompt") {
    /* write to the clipboard now */
  }
});

```

or use the manifest.json. (source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#writing_to_the_clipboard)

**Comment by ArjanPeeters** [comment]
I've implemented your solution. Could you try it?

**Comment by yschaeff** [comment]
I observe no difference. Still the javascript alert.

**Comment by yschaeff** [comment]
I cannot see the change at all. If you push your commit to github I can compare the code and make sure I'm looking at the right place.

**Comment by ArjanPeeters** [comment]
Its updated now.
https://github.com/ArjanPeeters/NaamKenmerkToepassing/blob/master/src/ts/utils/ClipboardHelper.ts

And it works on my computer 😅
